### ISSUE TITLE
Get index path for a specific item

### ISSUE THREAD

**Issue by eytanbiala** [genkernel/TreeView#5]
What is the best way to get the tree index path for an item?

I looked through the code and the examples for a method like `-(NSIndexPath *)indexPathForItem:(NSDictionary *)item;`

**Comment by genkernel** [comment]
Almost! :)

All public API is in TreeTable.h file.

There is a method that does exactly what you asked:
- (NSIndexPath *)treeIndexPathForItem:(UITableViewCell *)item;

Except it accepts a cell - not a dictionary.

**Comment by eytanbiala** [comment]
Thanks! Unfortunately in the case I'm working on I don't have access to the cell, only the item

**Comment by genkernel** [comment]
I'm sure you know better than me how to make an index path from a data source item of yours.

If you want to convert general index path (2 indices) into multidimensional tree index path you can use:
- (NSIndexPath *)treeIndexPathFromTablePath:(NSIndexPath *)indexPath;
and vice versa:
- (NSIndexPath *)tableIndexPathFromTreePath:(NSIndexPath *)indexPath;

Make sure to check 3 other branches for extra examples on how to use this component.

Cheers!
