### ISSUE TITLE
Use custom UITableViewCell 

### ISSUE THREAD

**Issue by smartv** [genkernel/TreeView#6]
Hello，I want to use custom UITableViewCell ,but it not offset. 
have you can handle this?

**Comment by genkernel** [comment]
Hi, 

you can use "indentationLevel" or introduce your own property.
Then in a custom cell you offset custom subviews that you added by N pixels where N can be calculated based on indentationLevel value.

**Comment by smartv** [comment]
thanks for replied, I will have a try.  if your provide an example would be better...I was a novice of iOS programmer

**Comment by genkernel** [comment]
Check out stackoverflow - there are tons of available examples implementing exactly this and using different technics (autolayout, direct frame manipulation).
Although designing a cell and presenting content inside is not related to TreeView component.
