### ISSUE TITLE
How can I resize hight Row?

### ISSUE THREAD

**Issue by thenopen** [genkernel/TreeView#7]
I try to use this

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
    if (indexPath.section == 0 && indexPath.length >= 4) {
        return 200;
    }
    return 50;
}
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath {
if (indexPath.section == 0 ) {
 return 200;
}
return 50;
}

there are work only all cell were changed.

<NSIndexPath: 0xc000000000000026> {length = 4, path = 0 - 0 - 0 - 0}
<NSIndexPath: 0xc000000001000026> {length = 4, path = 0 - 0 - 1 - 0}

I try to use certain cell to change hight row, but I could't.
Please let me now How can I change cell's hight?

**Comment by genkernel** [comment]
Not sure that I understand the problem.

One thing here: if your indexPath has more than 2 indeces - then accessing ".section" or ".row" property will crash.
You can access them using "indexAtPosition:" method (e.g. section = [indexPath indexAtPosition:0])

**Comment by genkernel** [comment]
Hey, did you manage to resolve the problem?
