### ISSUE TITLE
MGIsDeviceOneOfType is not supported on this platform.

### ISSUE THREAD

**Issue by NandParikh** [genkernel/TreeView#8]
When i added it, it gives me below error message and crashes.
TreeViewExample[50026:1884118] libMobileGestalt MobileGestalt.c:890: MGIsDeviceOneOfType is not supported on this platform.

**Comment by genkernel** [comment]
Hey, this is intriguing.
I would assume that the error message is not related to `TreeView` library itself.
There is a discussion about the same issue on [stackoverflow](https://stackoverflow.com/questions/51640360/libmobilegestalt-mobilegestalt-c890-mgisdeviceoneoftype-is-not-supported-on-th). Do other apps crash or work as expected on your simulator/device?
